-- CREATE DATABASE interviews;

-- CREATE TABLE users
-- (user_id SERIAL PRIMARY KEY NOT NULL,
-- name VARCHAR(50) NOT NULL,
-- email VARCHAR(255) NOT NULL,
-- password VARCHAR(255) NOT NULL,
-- sex VARCHAR(10) NOT NULL,
-- department VARCHAR(25) NOT NULL,
-- mobile VARCHAR(16) NOT NULL,
-- createdAt TIMESTAMP,
-- UNIQUE (email));